# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_email',
            field=models.EmailField(help_text='Billing Email (private)', max_length=254, null=True),
        ),
    ]
