# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.SlugField(allow_unicode=True, default=None, max_length=60, null=True),
        ),
    ]
