# -*- coding: utf-8 -*-
# account.migrations.0005_populate_name_values
# Populating values to the account name from the generic owner.
#
# Author:   Benjamin Bengfort <bbengfort@districtdatalabs.com>
# Created:  Sat Feb 13 15:38:38 2016 -0500
#
# Copyright (C) 2016 District Data Labs
# For license information, see LICENSE.txt
#
# ID: 0005_populate_name_values.py [] benjamin@bengfort.com $

"""
Populating values to the account name from the generic owner.
Generated by Django 1.9.1 on 2016-02-13 20:32
"""

##########################################################################
## Imports
##########################################################################

from __future__ import unicode_literals

from django.db import migrations
from account.models import Account

def add_account_names(apps, schema_editor):
    model_name_map = {
        'organization': 'orgname',
        'user': 'username',
    }

    for instance in Account.objects.all():
        model_name = instance.content_type.model

        if model_name in model_name_map:
            attr = model_name_map[model_name]
            instance.name = getattr(instance.owner, attr)
            instance.save()
        else:
            raise TypeError(
                'Unknown owner model for an account: {!r}'.format(model_name)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_name'),
        ('auth', '__latest__'),
        ('organization', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            add_account_names,
            reverse_code=migrations.RunPython.noop,
        )
    ]
