# -*- coding: utf-8 -*-
# account.migrations.0006_remove_name_null
# The last migration populated the account names, so now make them not null.
#
# Author:   Benjamin Bengfort <bbengfort@districtdatalabs.com>
# Created:  Sat Feb 13 15:39:38 2016 -0500
#
# Copyright (C) 2016 District Data Labs
# For license information, see LICENSE.txt
#
# ID: 0006_remove_name_null.py [] benjamin@bengfort.com $

"""
The last migration populated the account names, so now make them not null.
"""

##########################################################################
## Imports
##########################################################################


# Generated by Django 1.9.1 on 2016-02-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_populate_name_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.SlugField(max_length=60, null=False, unique=True, allow_unicode=True, editable=False),
        ),
    ]
