# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffer', '0003_auto_20160127_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description_markup_type',
            field=models.CharField(choices=[(b'', b'--'), (b'markdown', b'markdown')], default=b'markdown', editable=False, max_length=30),
        ),
    ]
