# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 02:49
from __future__ import unicode_literals

import account.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('orgname', models.SlugField(allow_unicode=True, max_length=60, unique=True)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, help_text='Contact Email (public)', max_length=254, null=True)),
                ('gravatar_email', models.EmailField(blank=True, default=None, help_text='Gravatar Email (private)', max_length=254, null=True)),
                ('email_hash', models.CharField(blank=True, default=None, editable=False, max_length=32, null=True)),
                ('billing_email', models.EmailField(help_text='Billing Email (private)', max_length=254)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'organization',
                'get_latest_by': 'created',
            },
            bases=(account.mixins.AccountMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('writer', 'writer'), ('reader', 'reader')], default='reader', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('protected', 'protected'), ('private', 'private')], default='protected', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_user_role',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='team',
            field=models.ManyToManyField(related_name='organizations', through='organization.Role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('organization', 'user')]),
        ),
    ]
