# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_hash',
            field=models.CharField(blank=True, default=None, editable=False, max_length=32, null=True),
        ),
    ]
