CREATE ROLE cultivar WITH LOGIN PASSWORD 'cultivar';
GRANT ALL PRIVILEGES ON DATABASE cultivar to cultivar;
ALTER USER cultivar CREATEDB;

CREATE ROLE vagrant WITH LOGIN PASSWORD 'cultivar';
GRANT ALL PRIVILEGES ON DATABASE cultivar to vagrant;
ALTER USER vagrant CREATEDB;
