# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160212_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=markupfield.fields.MarkupField(blank=True, default=None, help_text='Edit in Markdown', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30),
        ),
    ]
